application:
  web: web-src
  runtimeManifest:
    packages:
      aem-genai-assistant:
        license: Apache-2.0
        actions:
          complete:
            function: actions/complete/index.js
            web: true
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              FIREFALL_ENDPOINT: $FIREFALL_ENDPOINT
              FIREFALL_API_KEY: $FIREFALL_API_KEY
              IMS_ENDPOINT: $IMS_ENDPOINT
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_SERVICE_CLIENT_ID: $IMS_SERVICE_CLIENT_ID
              IMS_SERVICE_CLIENT_SECRET: $IMS_SERVICE_CLIENT_SECRET
              IMS_SERVICE_PERM_AUTH_CODE: $IMS_SERVICE_PERM_AUTH_CODE
              IMS_PRODUCT_CONTEXT: $IMS_PRODUCT_CONTEXT
            limits:
              timeout: 180000
          feedback:
            function: actions/feedback/index.js
            web: true
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              FIREFALL_ENDPOINT: $FIREFALL_ENDPOINT
              FIREFALL_API_KEY: $FIREFALL_API_KEY
              IMS_ENDPOINT: $IMS_ENDPOINT
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_SERVICE_CLIENT_ID: $IMS_SERVICE_CLIENT_ID
              IMS_SERVICE_CLIENT_SECRET: $IMS_SERVICE_CLIENT_SECRET
              IMS_SERVICE_PERM_AUTH_CODE: $IMS_SERVICE_PERM_AUTH_CODE
              IMS_PRODUCT_CONTEXT: $IMS_PRODUCT_CONTEXT
            limits:
              timeout: 180000
