application:
  web: web-src
  runtimeManifest:
    packages:
      aem-genai-assistant:
        license: Apache-2.0
        actions:
          complete:
            function: actions/complete/index.js
            web: true
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              FIREFALL_API_KEY: $FIREFALL_API_KEY
              FIREFALL_IMSS_ORG: $FIREFALL_IMSS_ORG
              IMSS_CLIENT_ID: $IMSS_CLIENT_ID
              IMSS_CLIENT_SECRET: $IMSS_CLIENT_SECRET
              IMSS_SERVICE_PERMANENT_ATHORIZATION_CODE: $IMSS_SERVICE_PERMANENT_ATHORIZATION_CODE
