application:
  web: web-src
  runtimeManifest:
    packages:
      aem-genai-assistant:
        license: Apache-2.0
        actions:
          complete:
            function: actions/complete/index.js
            web: true
            runtime: nodejs:18
            inputs:
              IMS_ENDPOINT: $IMS_ENDPOINT
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_SERVICE_CLIENT_ID: $IMS_SERVICE_CLIENT_ID
              IMS_SERVICE_CLIENT_SECRET: $IMS_SERVICE_CLIENT_SECRET
              IMS_SERVICE_PERM_AUTH_CODE: $IMS_SERVICE_PERM_AUTH_CODE
              IMS_PRODUCT_CONTEXT: $IMS_PRODUCT_CONTEXT
          generate:
            function: actions/generate/index.js
            web: false
            runtime: nodejs:18
            limits:
              timeout: 300000 # in ms (300 sec)
            inputs:
              FIREFALL_ENDPOINT: $FIREFALL_ENDPOINT
              FIREFALL_API_KEY: $FIREFALL_API_KEY
          feedback:
            function: actions/feedback/index.js
            web: true
            runtime: nodejs:18
            inputs:
              FIREFALL_ENDPOINT: $FIREFALL_ENDPOINT
              FIREFALL_API_KEY: $FIREFALL_API_KEY
              IMS_ENDPOINT: $IMS_ENDPOINT
              IMS_CLIENT_ID: $IMS_CLIENT_ID
              IMS_SERVICE_CLIENT_ID: $IMS_SERVICE_CLIENT_ID
              IMS_SERVICE_CLIENT_SECRET: $IMS_SERVICE_CLIENT_SECRET
              IMS_SERVICE_PERM_AUTH_CODE: $IMS_SERVICE_PERM_AUTH_CODE
              IMS_PRODUCT_CONTEXT: $IMS_PRODUCT_CONTEXT
          target:
            function: actions/target/index.js
            web: true
            runtime: nodejs:18
            inputs:
              TARGET_API_KEY: $TARGET_API_KEY
          csv:
            function: actions/csv/index.js
            web: true
            runtime: nodejs:18
          cf:
            function: actions/cf/index.js
            web: true
            runtime: nodejs:18
  hooks:
    pre-app-deploy: ./hooks/pre-app-deploy.js
