#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# If excel or csv files in the examples/ directory have changed, run the zip examples script
if [ -n "$(git diff --cached --name-only | grep -E 'examples/.*\.(csv|xlsx)$')" ]; then
 npm run examples
else
    echo "No excel or csv files changed. Skipping 'npm run examples'"
fi

# npm test && npm run lint
