name: Deploy to QA

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Run npm scripts
      env:
          CI: true
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_QA }}
          AIO_RUNTIME_NAMESPACE: 245265-879aquaant-qa
          AIO_RUNTIME_APIHOST: 'https://adobeioruntime.net'
          IMS_PRODUCT_CONTEXT: dma_aem_cloud
      run: |
        npm install
        npm run grammar
        npm run build
        npm run lint
        npm run test
        npm run deploy